name: CD - Deploy to Azure Web App (multi-container)

on:
  workflow_run:
    workflows: ["CI - Test + Build + Push ACR"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare docker-compose.prod.yml
        run: |
          cd project/src
          cp docker-compose.prod.yml docker-compose.yml
          zip deploy.zip docker-compose.yml

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          package: ./project/src/deploy.zip