name: CI - Test + Build + Push to ACR

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      web: ${{ steps.filter.outputs.web }}
    steps:
      - uses: actions/checkout@v3

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            api:
              - 'project/src/api/**'
            web:
              - 'project/src/frontend/**'
      
      - name: Debug change detection
        run: |
          echo "API changed? ${{ steps.filter.outputs.api }}"
          echo "WEB changed? ${{ steps.filter.outputs.web }}"

  test:
    runs-on: ubuntu-latest
    needs: detect-changes
    steps:
      - uses: actions/checkout@v3
      - name: Install docker-compose
        run: |
          curl -SL https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose version
      - name: Create .env file con los secretos
        run: |
          echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> ./project/src/.env
          echo "WANDB_ARTIFACT_PATH=${{ secrets.WANDB_ARTIFACT_PATH }}" >> ./project/src/.env
      - name: Run tests
        run: |
          docker-compose -f ./project/src/docker-compose.yml --env-file ./project/src/.env up --abort-on-container-exit test
      - name: Show logs if API container failed
        if: failure()
        run: |
          docker-compose -f ./project/src/docker-compose.yml logs api

  build-api:
    runs-on: ubuntu-latest
    needs: [test, detect-changes]
    if: needs.detect-changes.outputs.api == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker login to ACR
        run: az acr login --name ${{ secrets.AZURE_ACR_NAME }}
      - name: Build & push API image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/house-price-mlops:ci ./project/src/api
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/house-price-mlops:ci

  build-web:
    runs-on: ubuntu-latest
    needs: [test, detect-changes]
    if: needs.detect-changes.outputs.web == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker login to ACR
        run: az acr login --name ${{ secrets.AZURE_ACR_NAME }}
      - name: Build & push Web image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/web-house-price-mlops:ci ./project/src/frontend
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/web-house-price-mlops:ci